import { cert, getApps, initializeApp } from 'firebase-admin/app'
import type { Metadata } from 'next'
import { Sora, Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import AOSProvider from '@/utils/AOSProvider'

const sora = Sora({
	variable: '--font-sora', // Pastikan nama variable sesuai
	subsets: ['latin'],
	display: 'swap', // Opsional, untuk mempercepat rendering font
})

const plusJakartaSans = Plus_Jakarta_Sans({
	variable: '--font-plus-jakarta-sans', // Pastikan nama variable sesuai
	subsets: ['latin'],
	display: 'swap', // Opsional, untuk mempercepat rendering font
})

export const metadata: Metadata = {
	title: 'Little Athlete',
	description: 'Generated by create next app',
}

if (getApps().length == 0) {
	initializeApp({
		credential: cert({
			privateKey: process.env.NEXT_FIREBASE_ADMIN_PRIVATE_KEY,
			projectId: process.env.NEXT_FIREBASE_ADMIN_PROJECT_ID,
			clientEmail: process.env.NEXT_FIREBASE_ADMIN_CLIENT_EMAIL,
		}),
	})
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${sora.variable} ${plusJakartaSans.variable} antialiased`}>
				<AOSProvider />
				{children}
			</body>
		</html>
	)
}
