import type { Metadata } from 'next'
import { Sora, Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import AOSProvider from '@/utils/AOSProvider'
import { firebaseInit } from '@/config/firebase'

const sora = Sora({
	variable: '--font-sora', // Pastikan nama variable sesuai
	subsets: ['latin'],
	display: 'swap', // Opsional, untuk mempercepat rendering font
})

const plusJakartaSans = Plus_Jakarta_Sans({
	variable: '--font-plus-jakarta-sans', // Pastikan nama variable sesuai
	subsets: ['latin'],
	display: 'swap', // Opsional, untuk mempercepat rendering font
})

export const metadata: Metadata = {
	title: 'Little Athlete',
	description: 'Generated by create next app',
}

firebaseInit()

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${sora.variable} ${plusJakartaSans.variable} antialiased`}>
				<AOSProvider />
				{children}
			</body>
		</html>
	)
}
